repos:
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
     - id: black
       args: [--line-length=88]
       language_version: python3.11
-  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
        args: [--profile=black]
-  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v7.2.0
    hooks:
      - id: flake8
        args: [--max-line-length=88]
        additional_dependencies:
          - flake8-bugbear
          - flake8-annotations
-  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --strict]
-  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=google]